name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: Build Docker Images
      #   run: |
      #     docker build -t cygnetops/multi-client-k8s-gh:latest -t cygnetops/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
      #     docker build -t cygnetops/multi-server-k8s-pgfix-gh:latest -t cygnetops/multi-server-k8s-pgfix-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
      #     docker build -t cygnetops/multi-worker-k8s-gh:latest -t cygnetops/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Set Identity Provider
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/483100437721/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'gh-deployer@model-framing-428016-k7.iam.gserviceaccount.com'

      # - name: Set Project
      #   uses: google-github-actions/setup-gcloud@v0
      #   with:
      #     project_id: model-framing-428016-k7

      # - name: Authenticate Docker with GCP
      #   run: |
      #     gcloud --quiet auth configure-docker

      # - name: Get GKE Credentials
      #   uses: google-github-actions/get-gke-credentials@v0
      #   with:
      #     cluster_name: multi-cluster
      #     location: us-central1-c


      # - name: Rebuild Docker Images with SHA
      #   run: |
      #     docker build -t cygnetops/multi-client-k8s-gh:latest -t cygnetops/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
      #     docker build -t cygnetops/multi-server-k8s-pgfix-gh:latest -t cygnetops/multi-server-k8s-pgfix-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
      #     docker build -t cygnetops/multi-worker-k8s-gh:latest -t cygnetops/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      # - name: Push Docker Images
      #   run: |
      #     docker push cygnetops/multi-client-k8s-gh:latest
      #     docker push cygnetops/multi-server-k8s-pgfix-gh:latest
      #     docker push cygnetops/multi-worker-k8s-gh:latest
          
      #     docker push cygnetops/multi-client-k8s-gh:${{ env.SHA }}
      #     docker push cygnetops/multi-server-k8s-pgfix-gh:${{ env.SHA }}
      #     docker push cygnetops/multi-worker-k8s-gh:${{ env.SHA }}

      - name: Apply Kubernetes Configuration
        run: |
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=cygnetops/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=cygnetops/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=cygnetops/multi-worker-k8s-gh:${{ env.SHA }}
